Gemfile:
  puppet_version: '>= 3.0'
Rakefile:
  strict_variables: false
spec/spec_helper_acceptance.rb:
  modules:
    - name: stahnma-epel
      version: 0.1.0
      osfamily: RedHat
    - name: puppetlabs-apache
      version: 1.1.0
spec/spec_helper.rb:
  coverage_report: false
  minimum_code_coverage_percentage: 0
  strict_level: ":warning"
.rubocop.yml:
  default_configs: &default_configs
    Lint/HandleExceptions:
      Enabled: false
